### PR TITLE
Reverse names for S3 sort

### LINKED ISSUE #1: SQLITE_CORRUPT After 100,000 Inserts
When I create a table with one column and insert about 100,000 records, the subsequent open results in SQLITE_CORRUPT (11). If I create more columns, the inserts fail before 40,000 inserts. It seems dependent on the amount of data.

The last file name I see in S3 is '0000001015'.

That's all the information I have at this time. I'm having trouble setting up a debugger with this module at this time.

Thanks

### PR DESCRIPTION
**Pull request by rrmckinley**
Use base 36 filenames, reverse names for S3 sort

Fyi, this does not seek to fix likely pagination problems with delete

### CODE REVIEW

File: src/s3vfs.ts [hunk 1]
```diff
@@ -126,8 +132,13 @@ export class S3VFS extends Base {
...
         const objects = await this.fetchObjects(fileId)
-        const size = (objects || []).reduce((size, { Size: blockSize }) => size + (blockSize || 0), 0)
-        pSize64.set(size)
+        // Capture the last non-slash characters
+        const filename = objects?.[0]?.Key?.match(/([^/]*)$/)?.[0];
+        // console.log(filename);
+        // Use BigInt to avoid precision problems with Number
+        const fileCount = filename ? base36.decodeBigInt(filename) : 0;
+        const size = fileCount ? (fileCount * this.blockSizeN) + this.blockSizeN : 0;
+        pSize64.set(Number(size))
```
Comment (LoneRifle) [inline src/s3vfs.ts:141]: For the avoidance of doubt, could you explain what is happening here?

afaict, when S3 responds with the list of files, and per #1, the lowest (and hence most recent in sequence, since we are using a descending sequence from `zzzzzzzzzz` to `0000000000`) filename will be assigned to `filename`. `size` will then be calculated from that filename. 

This should then result in `xFileSize()` whose value _decreases_ as the actual file size _increases_. Or am I mistaken here?

**Review by LoneRifle — COMMENTED** [review]
one question to answer

**Review by LoneRifle — CHANGES_REQUESTED** [review]
unit tests are broken due to Babel transforming the BigInt exponentiation operator to `Math.pow`, which is incompatible with most BigInt implementations in Node. Consider either avoiding BigInts altogether, or somehow reworking `babel.config.cjs` so that it knows to avoid the use of the offending Babel plugin.

File: src/s3vfs.ts (hunk 1 above)
Comment (rrmckinley) [reply src/s3vfs.ts:141]: You're correct. I need to reverse the offset here to get the difference between the largest and smallest filename. I'll add a commit

**Comment by rrmckinley** [comment]
> unit tests are broken due to Babel transforming the BigInt exponentiation operator to `Math.pow`

Thanks, I'll run the tests and work through that

**Comment by rrmckinley** [comment]
I removed base 36 usage to focus only on correct behavior for the filename reversal. I have not yet run tests. I see that it uses docker and I'll test that when I have time to configure that setup. I'll let you know when I'm able to run tests.

**Review by LoneRifle — APPROVED** [review]
lgtm - I'll merge this at a later point
